name: Altdx Testing Library

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: ["v1.x"]
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Lint Deno Module
        run: deno fmt --check
      - name: Build Deno Module
        run: deno run --reload ./Mock/mod.ts
      - name: Test Deno Module
        run: deno test --allow-none
